#!/usr/bin/env bash

docker run \
  -d \
  --device /dev/snd \
  --env AIRPLAY_NAME=Downstairs \
  --name shairport-sync \
  --net host \
  --restart always \
  kourkis/shairport-sync:latest -- -d hw:0 -c PCM 

